# initial joint positions [degrees] for gazebo simulation
A1 : -50   # -50 deg
A2 : -35   # -35 deg
A3 : 0       # 0 deg
A4 : 75    # 75 deg
A5 : 0     # 0 deg
A6 : -65   # -65 deg
A7 : -50   # -50 deg
